package com.unmsm.fisi.entity;
//Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ManProducto generated by hbm2java
 */
@Entity
@Table(name = "man_oferta", catalog = "QualityEggs")
public class ManOferta implements java.io.Serializable {
	private Integer nidOferta;
	private String vdescripcion;
	private Integer ndescuento;
	private Date dfechaInicio;
	private Date dfechaFin;
	
	public ManOferta() {
		
	}
	
	public ManOferta(Integer nidOferta, String vdescripcion, Integer ndescuento, Date dfechaInicio, Date dfechaFin) {
		this.nidOferta = nidOferta;
		this.vdescripcion = vdescripcion;
		this.ndescuento = ndescuento;
		this.dfechaInicio = dfechaInicio;
		this.dfechaFin = dfechaFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdOferta", unique = true, nullable = false)
	public Integer getNidOferta() {
		return nidOferta;
	}

	public void setNidOferta(Integer nidOferta) {
		this.nidOferta = nidOferta;
	}

	@Column(name = "vDescripcion", length = 50)
	public String getVdescripcion() {
		return vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

	@Column(name = "vDescripcion")
	public Integer getNdescuento() {
		return ndescuento;
	}

	public void setNdescuento(Integer ndescuento) {
		this.ndescuento = ndescuento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFechaInicio", length = 10)
	public Date getDfechaInicio() {
		return dfechaInicio;
	}

	public void setDfechaInicio(Date dfechaInicio) {
		this.dfechaInicio = dfechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFechaFin", length = 10)
	public Date getDfechaFin() {
		return dfechaFin;
	}

	public void setDfechaFin(Date dfechaFin) {
		this.dfechaFin = dfechaFin;
	}

	
}
