package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ManProveedor generated by hbm2java
 */
@Entity
@Table(name = "man_proveedor", catalog = "QualityEggs")
public class ManProveedor implements java.io.Serializable {

	private ManProveedorId id;
	private String vempresa;
	private String vrubro;

	public ManProveedor() {
	}

	public ManProveedor(ManProveedorId id, String vempresa) {
		this.id = id;
		this.vempresa = vempresa;
	}

	public ManProveedor(ManProveedorId id, String vempresa, String vrubro) {
		this.id = id;
		this.vempresa = vempresa;
		this.vrubro = vrubro;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "manPersonaVNumeroDocumento", column = @Column(name = "man_persona_vNumeroDocumento", nullable = false, length = 20)),
			@AttributeOverride(name = "manPersonaVTipoDocumento", column = @Column(name = "man_persona_vTipoDocumento", nullable = false, length = 20)) })
	public ManProveedorId getId() {
		return this.id;
	}

	public void setId(ManProveedorId id) {
		this.id = id;
	}

	@Column(name = "vEmpresa", nullable = false, length = 50)
	public String getVempresa() {
		return this.vempresa;
	}

	public void setVempresa(String vempresa) {
		this.vempresa = vempresa;
	}

	@Column(name = "vRubro", length = 50)
	public String getVrubro() {
		return this.vrubro;
	}

	public void setVrubro(String vrubro) {
		this.vrubro = vrubro;
	}

}
