package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ManProducto generated by hbm2java
 */
@Entity
@Table(name = "man_producto", catalog = "QualityEggs")
public class ManProducto implements java.io.Serializable {

	private Integer nidProducto;
	private String vnombre;
	private String vdescripcion;
	private String vtipo;
	private Integer nstock;
	private Double nprecioUnitario;

	public ManProducto() {
	}

	public ManProducto(String vnombre, String vdescripcion, String vtipo, Integer nstock, Double nprecioUnitario) {
		this.vnombre = vnombre;
		this.vdescripcion = vdescripcion;
		this.vtipo = vtipo;
		this.nstock = nstock;
		this.nprecioUnitario = nprecioUnitario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdProducto", unique = true, nullable = false)
	public Integer getNidProducto() {
		return this.nidProducto;
	}

	public void setNidProducto(Integer nidProducto) {
		this.nidProducto = nidProducto;
	}

	@Column(name = "vNombre", length = 20)
	public String getVnombre() {
		return this.vnombre;
	}

	public void setVnombre(String vnombre) {
		this.vnombre = vnombre;
	}

	@Column(name = "vDescripcion", length = 50)
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

	@Column(name = "vTipo", length = 20)
	public String getVtipo() {
		return this.vtipo;
	}

	public void setVtipo(String vtipo) {
		this.vtipo = vtipo;
	}

	@Column(name = "nStock")
	public Integer getNstock() {
		return this.nstock;
	}

	public void setNstock(Integer nstock) {
		this.nstock = nstock;
	}

	@Column(name = "nPrecioUnitario", precision = 22, scale = 0)
	public Double getNprecioUnitario() {
		return this.nprecioUnitario;
	}

	public void setNprecioUnitario(Double nprecioUnitario) {
		this.nprecioUnitario = nprecioUnitario;
	}

}
