package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ManTrabajador generated by hbm2java
 */
@Entity
@Table(name = "man_trabajador", catalog = "QualityEggs")
public class ManTrabajador implements java.io.Serializable {

	private ManTrabajadorId id;
	private String varea;
	private String vpuesto;

	public ManTrabajador() {
	}

	public ManTrabajador(ManTrabajadorId id, String varea) {
		this.id = id;
		this.varea = varea;
	}

	public ManTrabajador(ManTrabajadorId id, String varea, String vpuesto) {
		this.id = id;
		this.varea = varea;
		this.vpuesto = vpuesto;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "manPersonaVNumeroDocumento", column = @Column(name = "man_persona_vNumeroDocumento", nullable = false, length = 20)),
			@AttributeOverride(name = "manPersonaVTipoDocumento", column = @Column(name = "man_persona_vTipoDocumento", nullable = false, length = 20)) })
	public ManTrabajadorId getId() {
		return this.id;
	}

	public void setId(ManTrabajadorId id) {
		this.id = id;
	}

	@Column(name = "vArea", nullable = false, length = 50)
	public String getVarea() {
		return this.varea;
	}

	public void setVarea(String varea) {
		this.varea = varea;
	}

	@Column(name = "vPuesto", length = 50)
	public String getVpuesto() {
		return this.vpuesto;
	}

	public void setVpuesto(String vpuesto) {
		this.vpuesto = vpuesto;
	}

}
