package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MultiTabDet generated by hbm2java
 */
@Entity
@Table(name = "multi_tab_det", catalog = "QualityEggs")
public class MultiTabDet implements java.io.Serializable {

	private MultiTabDetId id;
	private String vdescripcionCorta;
	private String vdescripcion;

	public MultiTabDet() {
	}

	public MultiTabDet(MultiTabDetId id) {
		this.id = id;
	}

	public MultiTabDet(MultiTabDetId id, String vdescripcionCorta, String vdescripcion) {
		this.id = id;
		this.vdescripcionCorta = vdescripcionCorta;
		this.vdescripcion = vdescripcion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "nidTabla", column = @Column(name = "nIdTabla", nullable = false)),
			@AttributeOverride(name = "vidItem", column = @Column(name = "vIdItem", nullable = false, length = 50)) })
	public MultiTabDetId getId() {
		return this.id;
	}

	public void setId(MultiTabDetId id) {
		this.id = id;
	}

	@Column(name = "vDescripcionCorta", length = 100)
	public String getVdescripcionCorta() {
		return this.vdescripcionCorta;
	}

	public void setVdescripcionCorta(String vdescripcionCorta) {
		this.vdescripcionCorta = vdescripcionCorta;
	}

	@Column(name = "vDescripcion", length = 400)
	public String getVdescripcion() {
		return this.vdescripcion;
	}

	public void setVdescripcion(String vdescripcion) {
		this.vdescripcion = vdescripcion;
	}

}
