package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import java.sql.Time;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegPedidoTrabajador generated by hbm2java
 */
@Entity
@Table(name = "reg_pedido_trabajador", catalog = "QualityEggs")
public class RegPedidoTrabajador implements java.io.Serializable {

	private Integer nidPedido;
	private String manTrabajadorManPersonaVTipoDocumento;
	private String manTrabajadorManPersonaVNumeroDocumento;
	private Integer ncantidad;
	private Boolean vestado;
	private Date dfecha;
	private Time thora;

	public RegPedidoTrabajador() {
	}

	public RegPedidoTrabajador(String manTrabajadorManPersonaVTipoDocumento,
			String manTrabajadorManPersonaVNumeroDocumento) {
		this.manTrabajadorManPersonaVTipoDocumento = manTrabajadorManPersonaVTipoDocumento;
		this.manTrabajadorManPersonaVNumeroDocumento = manTrabajadorManPersonaVNumeroDocumento;
	}

	public RegPedidoTrabajador(String manTrabajadorManPersonaVTipoDocumento,
			String manTrabajadorManPersonaVNumeroDocumento, Integer ncantidad, Boolean vestado, Date dfecha,
			Time thora) {
		this.manTrabajadorManPersonaVTipoDocumento = manTrabajadorManPersonaVTipoDocumento;
		this.manTrabajadorManPersonaVNumeroDocumento = manTrabajadorManPersonaVNumeroDocumento;
		this.ncantidad = ncantidad;
		this.vestado = vestado;
		this.dfecha = dfecha;
		this.thora = thora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdPedido", unique = true, nullable = false)
	public Integer getNidPedido() {
		return this.nidPedido;
	}

	public void setNidPedido(Integer nidPedido) {
		this.nidPedido = nidPedido;
	}

	@Column(name = "man_trabajador_man_persona_vTipoDocumento", nullable = false, length = 20)
	public String getManTrabajadorManPersonaVTipoDocumento() {
		return this.manTrabajadorManPersonaVTipoDocumento;
	}

	public void setManTrabajadorManPersonaVTipoDocumento(String manTrabajadorManPersonaVTipoDocumento) {
		this.manTrabajadorManPersonaVTipoDocumento = manTrabajadorManPersonaVTipoDocumento;
	}

	@Column(name = "man_trabajador_man_persona_vNumeroDocumento", nullable = false, length = 20)
	public String getManTrabajadorManPersonaVNumeroDocumento() {
		return this.manTrabajadorManPersonaVNumeroDocumento;
	}

	public void setManTrabajadorManPersonaVNumeroDocumento(String manTrabajadorManPersonaVNumeroDocumento) {
		this.manTrabajadorManPersonaVNumeroDocumento = manTrabajadorManPersonaVNumeroDocumento;
	}

	@Column(name = "nCantidad")
	public Integer getNcantidad() {
		return this.ncantidad;
	}

	public void setNcantidad(Integer ncantidad) {
		this.ncantidad = ncantidad;
	}

	@Column(name = "vEstado")
	public Boolean getVestado() {
		return this.vestado;
	}

	public void setVestado(Boolean vestado) {
		this.vestado = vestado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFecha", length = 10)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Column(name = "tHora", length = 8)
	public Time getThora() {
		return this.thora;
	}

	public void setThora(Time thora) {
		this.thora = thora;
	}

}
