package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import java.sql.Time;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegPago generated by hbm2java
 */
@Entity
@Table(name = "reg_pago", catalog = "QualityEggs")
public class RegPago implements java.io.Serializable {

	private Integer nidPago;
	private int regPedidoClienteNIdPedido;
	private Double npagoTotal;
	private Date dfecha;
	private Time thora;
	private String nTipoPago;
	private byte[] bVoucher;
	
	public RegPago() {
	}

	public RegPago(int regPedidoClienteNIdPedido) {
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
	}	

	public RegPago(Integer nidPago, int regPedidoClienteNIdPedido, Double npagoTotal, Date dfecha, Time thora,
			String nTipoPago, byte[] bVoucher) {
		super();
		this.nidPago = nidPago;
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
		this.npagoTotal = npagoTotal;
		this.dfecha = dfecha;
		this.thora = thora;
		this.nTipoPago = nTipoPago;
		this.bVoucher = bVoucher;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdPago", unique = true, nullable = false)
	public Integer getNidPago() {
		return this.nidPago;
	}

	public void setNidPago(Integer nidPago) {
		this.nidPago = nidPago;
	}

	@Column(name = "reg_pedido_cliente_nIdPedido", nullable = false)
	public int getRegPedidoClienteNIdPedido() {
		return this.regPedidoClienteNIdPedido;
	}

	public void setRegPedidoClienteNIdPedido(int regPedidoClienteNIdPedido) {
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
	}

	@Column(name = "nPagoTotal", precision = 22, scale = 0)
	public Double getNpagoTotal() {
		return this.npagoTotal;
	}

	public void setNpagoTotal(Double npagoTotal) {
		this.npagoTotal = npagoTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFecha", length = 10)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Column(name = "tHora", length = 8)
	public Time getThora() {
		return this.thora;
	}

	public void setThora(Time thora) {
		this.thora = thora;
	}

	@Column(name = "vTipoPago", length = 50)
	public String getnTipoPago() {
		return nTipoPago;
	}

	public void setnTipoPago(String nTipoPago) {
		this.nTipoPago = nTipoPago;
	}

    @Column(name = "bVoucher", columnDefinition="LONGBLOB")
	public byte[] getbVoucher() {
		return bVoucher;
	}

	public void setbVoucher(byte[] bVoucher) {
		this.bVoucher = bVoucher;
	}

}
