package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegPedidoHasManProductoId generated by hbm2java
 */
@Embeddable
public class RegPedidoHasManProductoId implements java.io.Serializable {

	private int regPedidoClienteNIdPedido;
	private int manProductoNIdProducto;

	public RegPedidoHasManProductoId() {
	}

	public RegPedidoHasManProductoId(int regPedidoClienteNIdPedido, int manProductoNIdProducto) {
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
		this.manProductoNIdProducto = manProductoNIdProducto;
	}

	@Column(name = "reg_pedido_cliente_nIdPedido", nullable = false)
	public int getRegPedidoClienteNIdPedido() {
		return this.regPedidoClienteNIdPedido;
	}

	public void setRegPedidoClienteNIdPedido(int regPedidoClienteNIdPedido) {
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
	}

	@Column(name = "man_producto_nIdProducto", nullable = false)
	public int getManProductoNIdProducto() {
		return this.manProductoNIdProducto;
	}

	public void setManProductoNIdProducto(int manProductoNIdProducto) {
		this.manProductoNIdProducto = manProductoNIdProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegPedidoHasManProductoId))
			return false;
		RegPedidoHasManProductoId castOther = (RegPedidoHasManProductoId) other;

		return (this.getRegPedidoClienteNIdPedido() == castOther.getRegPedidoClienteNIdPedido())
				&& (this.getManProductoNIdProducto() == castOther.getManProductoNIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRegPedidoClienteNIdPedido();
		result = 37 * result + this.getManProductoNIdProducto();
		return result;
	}

}
