package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegPago generated by hbm2java
 */
@Entity
@Table(name = "reg_pago", catalog = "QualityEggs")
public class RegPago implements java.io.Serializable {

	private Integer nidPago;
	private int regPedidoClienteNIdPedido;
	private Double npagoTotal;
	private Date dfecha;
	private Date thora;

	public RegPago() {
	}

	public RegPago(int regPedidoClienteNIdPedido) {
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
	}

	public RegPago(int regPedidoClienteNIdPedido, Double npagoTotal, Date dfecha, Date thora) {
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
		this.npagoTotal = npagoTotal;
		this.dfecha = dfecha;
		this.thora = thora;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nIdPago", unique = true, nullable = false)
	public Integer getNidPago() {
		return this.nidPago;
	}

	public void setNidPago(Integer nidPago) {
		this.nidPago = nidPago;
	}

	@Column(name = "reg_pedido_cliente_nIdPedido", nullable = false)
	public int getRegPedidoClienteNIdPedido() {
		return this.regPedidoClienteNIdPedido;
	}

	public void setRegPedidoClienteNIdPedido(int regPedidoClienteNIdPedido) {
		this.regPedidoClienteNIdPedido = regPedidoClienteNIdPedido;
	}

	@Column(name = "nPagoTotal", precision = 22, scale = 0)
	public Double getNpagoTotal() {
		return this.npagoTotal;
	}

	public void setNpagoTotal(Double npagoTotal) {
		this.npagoTotal = npagoTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFecha", length = 10)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tHora", length = 8)
	public Date getThora() {
		return this.thora;
	}

	public void setThora(Date thora) {
		this.thora = thora;
	}

}
