package com.unmsm.fisi.entity;
// Generated 19/05/2019 11:40:02 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SegUsuario generated by hbm2java
 */
@Entity
@Table(name = "seg_usuario", catalog = "QualityEggs")
public class SegUsuario implements java.io.Serializable {

	private String vidUsuario;
	private String manPersonaVNumeroDocumento;
	private String manPersonaVTipoDocumento;
	private int segPerfilNIdPerfil;
	private String vclave;
	private Boolean bactivo;
	private Date dfecha;
	private Date thora;

	public SegUsuario() {
	}

	public SegUsuario(String vidUsuario, String manPersonaVNumeroDocumento, String manPersonaVTipoDocumento,
			int segPerfilNIdPerfil) {
		this.vidUsuario = vidUsuario;
		this.manPersonaVNumeroDocumento = manPersonaVNumeroDocumento;
		this.manPersonaVTipoDocumento = manPersonaVTipoDocumento;
		this.segPerfilNIdPerfil = segPerfilNIdPerfil;
	}

	public SegUsuario(String vidUsuario, String manPersonaVNumeroDocumento, String manPersonaVTipoDocumento,
			int segPerfilNIdPerfil, String vclave, Boolean bactivo, Date dfecha, Date thora) {
		this.vidUsuario = vidUsuario;
		this.manPersonaVNumeroDocumento = manPersonaVNumeroDocumento;
		this.manPersonaVTipoDocumento = manPersonaVTipoDocumento;
		this.segPerfilNIdPerfil = segPerfilNIdPerfil;
		this.vclave = vclave;
		this.bactivo = bactivo;
		this.dfecha = dfecha;
		this.thora = thora;
	}

	@Id

	@Column(name = "vIdUsuario", unique = true, nullable = false, length = 20)
	public String getVidUsuario() {
		return this.vidUsuario;
	}

	public void setVidUsuario(String vidUsuario) {
		this.vidUsuario = vidUsuario;
	}

	@Column(name = "man_persona_vNumeroDocumento", nullable = false, length = 20)
	public String getManPersonaVNumeroDocumento() {
		return this.manPersonaVNumeroDocumento;
	}

	public void setManPersonaVNumeroDocumento(String manPersonaVNumeroDocumento) {
		this.manPersonaVNumeroDocumento = manPersonaVNumeroDocumento;
	}

	@Column(name = "man_persona_vTipoDocumento", nullable = false, length = 20)
	public String getManPersonaVTipoDocumento() {
		return this.manPersonaVTipoDocumento;
	}

	public void setManPersonaVTipoDocumento(String manPersonaVTipoDocumento) {
		this.manPersonaVTipoDocumento = manPersonaVTipoDocumento;
	}

	@Column(name = "seg_perfil_nIdPerfil", nullable = false)
	public int getSegPerfilNIdPerfil() {
		return this.segPerfilNIdPerfil;
	}

	public void setSegPerfilNIdPerfil(int segPerfilNIdPerfil) {
		this.segPerfilNIdPerfil = segPerfilNIdPerfil;
	}

	@Column(name = "vClave", length = 70)
	public String getVclave() {
		return this.vclave;
	}

	public void setVclave(String vclave) {
		this.vclave = vclave;
	}

	@Column(name = "bActivo")
	public Boolean getBactivo() {
		return this.bactivo;
	}

	public void setBactivo(Boolean bactivo) {
		this.bactivo = bactivo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dFecha", length = 10)
	public Date getDfecha() {
		return this.dfecha;
	}

	public void setDfecha(Date dfecha) {
		this.dfecha = dfecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tHora", length = 8)
	public Date getThora() {
		return this.thora;
	}

	public void setThora(Date thora) {
		this.thora = thora;
	}

}
